Repository v3rm0n/intercom_flutter, pull requests merged in 2019-09, with the labels that each got.

#30 add displayMessageComposer method
  android/src/main/kotlin/io/maido/intercom/IntercomFlutterPlugin.kt
  ios/Classes/IntercomFlutterPlugin.m
  lib/intercom_flutter.dart
  test/intercom_flutter_test.dart
Labels: enhancement, need tests

#35 Release 2.0.5
  CHANGELOG.md
  README.md
  android/build.gradle
  ios/intercom_flutter.podspec
  pubspec.yaml
Labels: bug, enhancement

#36 Make pub analyzer happy
  lib/intercom_flutter.dart
Labels: enhancement

#39 Version 2.0.5+2
  CHANGELOG.md
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  example/lib/main.dart
  example/pubspec.yaml
  ios/intercom_flutter.podspec
  pubspec.yaml
Labels: bug, ios
