Repository v3rm0n/intercom_flutter, pull requests merged in 2020-03, with the labels that each got.

#61 Fix incremental installation error
  CHANGELOG.md
  ios/Classes/IntercomFlutterPlugin.m
  ios/intercom_flutter.podspec
  pubspec.yaml
Labels: crash, enhancement, ios

#63 Unread messages count listener
  CHANGELOG.md
  android/src/main/kotlin/io/maido/intercom/IntercomFlutterPlugin.kt
  ios/Classes/IntercomFlutterPlugin.h
  ios/Classes/IntercomFlutterPlugin.m
  lib/intercom_flutter.dart
  pubspec.yaml
Labels: enhancement, need tests

#65 Unread message count test
  test/intercom_flutter_test.dart
Labels: enhancement
