Repository v3rm0n/intercom_flutter, pull requests merged in 2023-11, with the labels that each got.

#366 Update iOS SDK to 16.2.3
  intercom_flutter/CHANGELOG.md
  intercom_flutter/README.md
  intercom_flutter/android/build.gradle
  intercom_flutter/ios/intercom_flutter.podspec
  intercom_flutter/pubspec.yaml
Labels: native-sdk

#374 Update Android sdk 15.5.0 and iOS sdk 16.3.0
  intercom_flutter/CHANGELOG.md
  intercom_flutter/README.md
  intercom_flutter/android/build.gradle
  intercom_flutter/ios/intercom_flutter.podspec
  intercom_flutter/pubspec.yaml
Labels: enhancement

#375 Update uuid dependency to version 4.1.0
  intercom_flutter_web/CHANGELOG.md
  intercom_flutter_web/pubspec.yaml
Labels: platform-dart

#380 [intercom_flutter] Bump `intercom_flutter_web` to `1.0.1`
  intercom_flutter/CHANGELOG.md
  intercom_flutter/pubspec.yaml
Labels: platform-dart
