Repository v3rm0n/intercom_flutter, pull requests merged in 2023-09, with the labels that each got.

#353 Implement `displayTickets` for web
  intercom_flutter_web/CHANGELOG.md
  intercom_flutter_web/example/integration_test/intercom_flutter_web_test.dart
  intercom_flutter_web/lib/intercom_flutter_web.dart
  intercom_flutter_web/pubspec.yaml
Labels: enhancement

#352 Implement `displayTickets` on iOS and Android
  intercom_flutter/CHANGELOG.md
  intercom_flutter/README.md
  intercom_flutter/android/build.gradle
  intercom_flutter/android/src/main/kotlin/io/maido/intercom/IntercomFlutterPlugin.kt
  intercom_flutter/ios/Classes/IntercomFlutterPlugin.m
  intercom_flutter/ios/intercom_flutter.podspec
  intercom_flutter/lib/intercom_flutter.dart
  intercom_flutter/pubspec.yaml
  intercom_flutter/test/intercom_flutter_test.dart
Labels: enhancement

#357 Add doc about using FlutterFragmentActivity
  intercom_flutter/README.md
  intercom_flutter/example/android/app/src/main/kotlin/io/maido/intercomexample/MainActivity.kt
Labels: platform-android

#356 Update native SDK to 15.2.3 for iOS and 15.2.2 for Android
  intercom_flutter/CHANGELOG.md
  intercom_flutter/README.md
  intercom_flutter/android/build.gradle
  intercom_flutter/example/android/app/build.gradle
  intercom_flutter/example/android/build.gradle
  intercom_flutter/ios/intercom_flutter.podspec
  intercom_flutter/pubspec.yaml
Labels: enhancement

#355 Updated Intercom iOS SDK Version 16.0.0
  intercom_flutter/CHANGELOG.md
  intercom_flutter/README.md
  intercom_flutter/ios/intercom_flutter.podspec
  intercom_flutter/lib/intercom_flutter.dart
  intercom_flutter/pubspec.yaml
  intercom_flutter_platform_interface/CHANGELOG.md
  intercom_flutter_platform_interface/lib/intercom_flutter_platform_interface.dart
  intercom_flutter_platform_interface/lib/method_channel_intercom_flutter.dart
  intercom_flutter_platform_interface/pubspec.yaml
  intercom_flutter_web/CHANGELOG.md
  intercom_flutter_web/lib/intercom_flutter_web.dart
  intercom_flutter_web/pubspec.yaml
Labels: platform-ios
